---
#UPDATE - UPGRADE
- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

# FIX PACKAGES
- name: Remove "virtualbox-6.1" package
  apt:
   name: virtualbox-6.1
   state: absent
 
#INSTALL COMMON PACKAGES 
- name: Instala paquetes devops common
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - awscli
      - docker
      - docker-ce
      - docker-compose
      - google-cloud-sdk
      - google-cloud-sdk-app-engine-go
      - google-cloud-sdk-app-engine-java
      - google-cloud-sdk-app-engine-python
      - google-cloud-sdk-app-engine-python-extras
      - google-cloud-sdk-bigtable-emulator
      - google-cloud-sdk-bigtable-emulator
      - google-cloud-sdk-cbt
      - google-cloud-sdk-cloud-build-local
      - google-cloud-sdk-datalab
      - google-cloud-sdk-datastore-emulator
      - google-cloud-sdk-firestore-emulator
      - google-cloud-sdk-pubsub-emulator
      - kubectl
      # - meld
      - libssl-dev
      - libffi-dev
      - pgadmin3
      # - podman
      - postgresql-client
      # - sublime-merge
      # - sublime-text
      # - virtualbox-6.1
      - virtualbox
      - httpie
      - terraspace
      - apache2-utils
      # - buildah
      - libcurl4-openssl-dev
      - k6
      - mysql-client
      - mysql-client-8.0
      - qemu-kvm
      - exa
      - pwgen
    state: present
  #register: common-packages-installation
  tags: common

# Snap
- name: Install snaps
  snap:
    name:
      - beekeeper-studio
      - dbeaver-ce
      # - insomnia
      - k9s
      # - postman
      - sosumi
      - kustomize
      - storage-explorer

- name: Install snaps classic
  snap:
    name:
      # - code
      - helm
      - powershell
      - pycharm-community
      - kontena-lens
      # - android-studio
    classic: yes

# Flatpak
- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install multiple packages
  community.general.flatpak:
    name:
      - com.sublimemerge.App
      - com.sublimetext.three
      - com.visualstudio.code
      - com.google.AndroidStudio
      - org.gnome.meld
      - rest.insomnia.Insomnia
      - com.getpostman.Postman
    method: system

#INSTALL PIPS
- name: Fixing packages deps
  shell: pip3 install --ignore-installed pyzmq PyYAML psutil

- name: Install Python packages.
  pip:
    name: "{{ packages }}"
    # executable: pip3
  vars:
    packages:
      - pyOpenSSL
      - virtualenv
      - locust
      - boto
      - pre-commit
      - secrets
      - kubernetes
      - avro-python3
      #- awscli
    state: present

  #INSTALL GEMS
- name: Install RB packages rake.
  gem:
    name: rake
    state: present

- name: Install RB packages gemspec.
  gem:
    name: gemspec
    state: present

- name: Install RB packages fog.
  gem:
    name: fog
    state: present

- name: Install RB packages capistrano.
  gem:
    name: capistrano
    state: present

# Install from debs
- name: Install a .deb package for Minikube
  apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
  when: ansible_os_family == "Debian"
  ignore_errors: true

  # - name: Install a .deb package for AWS VPN Client
  # apt:
  #   deb: https://d20adtppz83p9s.cloudfront.net/GTK/latest/awsvpnclient_amd64.deb
   # when: ansible_os_family == "Debian"
   # ignore_errors: true

# Install from scripts
- name: Get latest Release from glab
  shell: curl -s https://raw.githubusercontent.com/profclems/glab/trunk/scripts/install.sh | sudo sh
  args:
    warn: no
  tags: glab

- name: Get latest Release Infracost
  shell: curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sudo sh
  args:
    warn: no
  tags: infrascost

