---
#UPDATE - UPGRADE
- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

#INSTALL COMMON PACKAGES 
- name: Instala paquetes devops common
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - awscli
      - docker
      - docker-ce
      - docker-compose
      - google-cloud-sdk
      - google-cloud-sdk-app-engine-go
      - google-cloud-sdk-app-engine-java
      - google-cloud-sdk-app-engine-python
      - google-cloud-sdk-app-engine-python-extras
      - google-cloud-sdk-bigtable-emulator
      - google-cloud-sdk-bigtable-emulator
      - google-cloud-sdk-cbt
      - google-cloud-sdk-cloud-build-local
      - google-cloud-sdk-datalab
      - google-cloud-sdk-datastore-emulator
      - google-cloud-sdk-firestore-emulator
      - google-cloud-sdk-pubsub-emulator
      - kubectl
      - meld
      - pgadmin3
      - podman
      - postgresql-client
      - sublime-merge
      - sublime-text
      - virtualbox-6.0
      - httpie
      - terraspace
      - apache2-utils
      - buildah
      - libcurl4-openssl-dev
      - k6
    state: present
  #register: common-packages-installation
  tags: common

# Snap
- name: Install snaps
  snap:
    name:
      - beekeeper-studio
      - dbeaver-ce
      - insomnia
      - k9s
      - postman
      - sosumi
      - kustomize

- name: Install snaps classic
  snap:
    name:
      - code
      - helm
      - powershell
      - pycharm-community
      - kontena-lens
    classic: yes

# Flatpak
- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

#INSTALL PIPS
- name: Install Python packages.
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
      - pyOpenSSL
      - virtualenv
      - locust
      #- awscli
    state: present

  #INSTALL GEMS
- name: Install RB packages rake.
  gem:
    name: rake
    state: present

- name: Install RB packages gemspec.
  gem:
    name: gemspec
    state: present

- name: Install RB packages fog.
  gem:
    name: fog
    state: present

- name: Install RB packages capistrano.
  gem:
    name: capistrano
    state: present