---
- name: apt-get clean
  shell: apt-get clean
  become: true
  become_user: root

- name: apt-get update
  shell: apt-get update
  become: true
  become_user: root
  ignore_errors: true

#ADD REPOS

#Sublime Text & Sublime Merge
- apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    keyring: /usr/share/keyrings/sublimehq-pub.gpg
    state: present

- apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/sublimehq-pub.gpg] https://download.sublimetext.com/ apt/stable/'
    state: present
    update_cache: no

#Virtualbox
- apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    keyring: /usr/share/keyrings/oracle_vbox_2016.gpg
    state: present


- apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    keyring: /usr/share/keyrings/oracle_vbox.gpg
    state: present


- apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/oracle_vbox.gpg] https://download.virtualbox.org/virtualbox/debian {{ codename }} contrib'
    state: present
    update_cache: no

#Docker
- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker.gpg
    state: present
# - apt_repository:
#     repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu '{{ codename }}' stable'
#     state : present
#     when: ansible_distribution == 'Linux Mint'

- apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ codename }} stable
    state : present
    update_cache: no

#GCLOUD SDK
- apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present
   
- apt_repository:
      repo: deb[signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
      state : present
      update_cache: no

# terraspace
- apt_key:
    url: https://apt.boltops.com/boltops-key.public
    keyring: /usr/share/keyrings/boltops-key.gpg
    state: present

- apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/boltops-key.gpg] https://apt.boltops.com stable main
    state : present
    update_cache: no

# Podman (Ubuntu 20.04)
- apt_key:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_20.04/Release.key"
    keyring: /usr/share/keyrings/podman.gpg
    state: present
  when: ansible_distribution_release == 'ulyana' or 
      ansible_distribution_release == 'ulyssa' or 
      ansible_distribution_release == 'uma' or 
      ansible_distribution_release == 'focal'

- apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/podman.gpg] http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /"
    state: present
    update_cache: no
  when: ansible_distribution_release == 'ulyana' or 
      ansible_distribution_release == 'ulyssa' or 
      ansible_distribution_release == 'uma' or 
      ansible_distribution_release == 'focal'

# K6
- apt_key:
    keyserver: keyserver.ubuntu.com
    id: C5AD17C747E3415A3642D57D77C6C491D6AC1D69
    state: present

- apt_repository:
    repo: 'deb https://dl.k6.io/deb stable main'
    state : present
    update_cache: no

# Exa
- name: Add EXA PPA
  apt_repository:
    repo: ppa:spvkgn/exa
    codename: '{{ codename }}'
    state : present
    update_cache: no


- name: apt-get update
  shell: apt-get update
  become: true
  become_user: root
  ignore_errors: true
